/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * index.java
 *
 * Created on Sep 8, 2012, 5:52:12 PM
 */


import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;


public class index1 extends javax.swing.JFrame {

static Connection connection;
    static String url;
    static Statement st;
    static ResultSet rs;

 public index1() {
        initComponents();
        index1.this.setLocation(450,250);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textLast = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtbday = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboGender = new javax.swing.JComboBox();
        comboStatus = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        goSave = new javax.swing.JButton();
        labelOption = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        studId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("Birthday:");

        txtbday.setText("MM");

        jLabel4.setText("Gender:");

        comboGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Married", "Widowed" }));

        jLabel5.setText("Status:");

        goSave.setText("save");
        goSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goSaveMouseClicked(evt);
            }
        });
        goSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goSaveActionPerformed(evt);
            }
        });

        labelOption.setText("Select Option:");

        jLabel6.setText("Student Id Number: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textLast)
                            .addComponent(textName)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comboGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtbday, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(studId))))
                    .addComponent(jLabel4))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelOption)
                        .addGap(88, 88, 88))
                    .addComponent(goSave, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtbday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(comboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelOption)
                        .addGap(33, 33, 33)))
                .addComponent(goSave)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goSaveActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
                url="jdbc:mysql://localhost:3306/student_info";
                connection = DriverManager.getConnection(url, "root","");
                st = connection.createStatement();
                if((studId.getText() == null ? "" == null : studId.getText().equals("")) || (textName.getText() == null ? "" == null : textName.getText().equals(""))){
                   JOptionPane.showMessageDialog(null, "ID or Name must contain value","System Message",JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                   st.executeUpdate("Insert into reg(" + "Id,firstname,lastname,birthday, gender, status" + ") VALUES ('" + studId.getText() + "','" + textName.getText() + "','" + textLast.getText() + "','"+ txtbday.getText()+ "','"+(String)comboGender.getSelectedItem()+"','" +(String)comboStatus.getSelectedItem()+ " ')");
                   JOptionPane.showMessageDialog(null, "Accoount Created","System Message",JOptionPane.INFORMATION_MESSAGE);
                    //index.this.setVisible(false);
                }
        }
        catch (ClassNotFoundException ex) {
            // Logger.getLogger(frameNewAccount.class.getName()).log(Level.SEVERE, null, ex);
        }catch (SQLException ex) {
            // Logger.getLogger(frameNewAccount.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, "Account already exist","System Message",JOptionPane.INFORMATION_MESSAGE);
                 studId.setText(null);
                 textName.setText(null);
                 textLast.setText(null);
        }

 


       
    }//GEN-LAST:event_goSaveActionPerformed

    private void goSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goSaveMouseClicked
        
    }//GEN-LAST:event_goSaveMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboGender;
    private javax.swing.JComboBox comboStatus;
    private javax.swing.JButton goSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelOption;
    private javax.swing.JTextField studId;
    private javax.swing.JTextField textLast;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField txtbday;
    // End of variables declaration//GEN-END:variables

}
